use QUANLYBANHANG
go

CREATE VIEW DOANHTHU_SP_VIEW AS
SELECT SP.MASP, SP.TENSP,
 SUM(CASE WHEN YEAR(NGHD) = 2006 THEN SL * GIA ELSE 0 END) AS
DOANHTHU2006, SUM(CASE WHEN YEAR(NGHD) = 2007 THEN SL * GIA ELSE 0 END) AS
DOANHTHU2007, SUM(CASE WHEN YEAR(NGHD) IN (2006, 2007) THEN SL * GIA ELSE 0 
END) AS TONGDOANHTHU
FROM SANPHAM SP LEFT JOIN CTHD ON SP.MASP = CTHD.MASP
LEFT JOIN HOADON HD ON CTHD.SOHD = HD.SOHD
WHERE YEAR(NGHD) IN (2006, 2007) OR NGHD IS NULL
GROUP BY SP.MASP, SP.TENSP
ORDER BY TONGDOANHTHU DESC OFFSET 0 ROWS
go

drop view DOANHTHU_SP_VIEW

select * from DOANHTHU_SP_VIEW