USE master
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'BAITHI17_18')
BEGIN
	ALTER DATABASE BAITHI17_18 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE BAITHI17_18;
END
GO

CREATE DATABASE BAITHI17_18
GO

USE BAITHI17_18
GO

SET DATEFORMAT DMY
GO

/*
SELECT * FROM KHACHHANG
SELECT * FROM LOAICAY
SELECT * FROM HOADON
SELECT * FROM CTHD
*/

-------------------------------KHACHHANG----------------------
CREATE TABLE KHACHHANG
(
	MAKH CHAR(4) PRIMARY KEY,
	TENKH VARCHAR(40),
	DIACHI VARCHAR(50),
	LOAIKH VARCHAR(20)
)
GO

-------------------------------LOAICAY-------------------------
CREATE TABLE LOAICAY
(
	MALC CHAR(4) PRIMARY KEY,
	TENLC VARCHAR(30),
	XUATXU VARCHAR(20),
	GIA MONEY
)
GO

------------------------------HOADON----------------------------
CREATE TABLE HOADON
(
	SOHD INT PRIMARY KEY,
	NGHD SMALLDATETIME,
	MAKH CHAR(4) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	KHUYENMAI TINYINT
)
GO

------------------------------CTHD-------------------------------
CREATE TABLE CTHD
(
	SOHD INT FOREIGN KEY REFERENCES HOADON(SOHD),
	MALC CHAR(4) FOREIGN KEY REFERENCES LOAICAY(MALC),
	SOLUONG INT
	PRIMARY KEY(SOHD, MALC)
)
GO


--2.Nhap du lieu
INSERT INTO KHACHHANG VALUES('KH01', 'Liz Kim Cuong', 'Ha Noi', 'Vang lai')
INSERT INTO KHACHHANG VALUES('KH02', 'Ivone Dieu Linh', 'Da Nang', 'Thuong xuyen')
INSERT INTO KHACHHANG VALUES('KH03', 'Emma Nhat Khanh', 'TP.HCM', 'Vang lai')

INSERT INTO LOAICAY VALUES('LC01', 'Xuong rong tai tho', 'Mexico', 180000)
INSERT INTO LOAICAY VALUES('LC02', 'Sen thach ngoc', 'Anh', 300000)
INSERT INTO LOAICAY VALUES('LC03', 'Ba mau rau', 'Nam Phi', 270000)

INSERT INTO HOADON VALUES(1, '22/11/2017', 'KH01', 5)
INSERT INTO HOADON VALUES(2, '04/12/2017', 'KH03', 5)
INSERT INTO HOADON VALUES(3, '10/12/2017', 'KH02', 10)

INSERT INTO CTHD VALUES(1, 'LC01', 1)
INSERT INTO CTHD VALUES(1, 'LC02', 2)
INSERT INTO CTHD VALUES(3, 'LC03', 5)
GO

--3.
ALTER TABLE LOAICAY ADD CONSTRAINT CK_GIA 
	CHECK(GIA > IIF(XUATXU = 'Anh', 250000, 0))
GO

--4.
ALTER TABLE HOADON ADD CONSTRAINT CK_KHUYENMAI
	CHECK((KHUYENMAI = 10 AND CTHD.SOLUONG >= 5) OR CTHD.SOLUONG < 5)
GO
