--------------------------------------B. STORED PROCEDURES VỚI THAM SỐ VÀO VÀ RA------------------------------------
USE QLDT
GO


--------------------------------------------------------------------------------
--CAU 1
--1. Đưa vào TENHV trả ra: Số GV thỏa học vị, nếu không tìm thấy trả về 0.

CREATE PROC PROC_COUNT_SOGV 
	@TENHV NVARCHAR(20), @SOGV INT OUTPUT
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM HOCVI WHERE TENHV = @TENHV)
	BEGIN
		PRINT N'TENHV CHUA TON TAI'
		RETURN 0
	END

	SELECT @SOGV = COUNT(DISTINCT MSGV)
	FROM GV_HV_CN, HOCVI
	WHERE HOCVI.MSHV = GV_HV_CN.MSHV AND TENHV = @TENHV
	PRINT N'THANH CONG'
END
GO

--1.1 THỰC THI VÀ KIỂM TRA
DECLARE @SOGV INT, @TENHV NVARCHAR(20)
SET @TENHV = N'Kỹ sư'

EXEC PROC_COUNT_SOGV @TENHV , @SOGV OUTPUT
PRINT N'SỐ GV CÓ HỌC VỊ ' + @TENHV + N' LÀ ' + CAST(@SOGV AS VARCHAR) --không thực hiện nếu @SOGV = NULL, vì những cái đi cùng NULL => fail
GO

--1.2 XÓA
DROP PROC PROC_COUNT_SOGV 
GO



----------------------------------------------------------------------------------------------------------------
--CAU 2
--2. Đưa vào MSDT cho biết: Điểm trung bình của đề tài, nếu không tìm thấy trả về 0.

CREATE PROCEDURE PROC_DETAI_AGV
	@MSDT CHAR(6), @AGV FLOAT OUTPUT
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM DETAI WHERE MSDT = @MSDT)
	BEGIN
		PRINT 'DE TAI KHONG TON TAI'
		RETURN 0
	END
	
	--SOGV_CHAMDIEM: số lượng giáo viên đã chấm điểm
	--TONGDIEM: tổng điểm của đề tài
	DECLARE @SOGV_CHAMDIEM INT = 0, @TONGDIEM FLOAT = 0

	--BANG GV_HDDT
	IF EXISTS (SELECT * FROM GV_HDDT WHERE MSDT = @MSDT)
	BEGIN
		SELECT @SOGV_CHAMDIEM = COUNT(*), @TONGDIEM = SUM(DIEM)
		FROM GV_HDDT
		WHERE MSDT = @MSDT
	END
	
	--BANG GV_PBDT
	IF EXISTS (SELECT * FROM GV_PBDT WHERE MSDT = @MSDT)
	BEGIN
		SELECT @SOGV_CHAMDIEM += COUNT(*), @TONGDIEM += SUM(DIEM)
		FROM GV_PBDT
		WHERE MSDT = @MSDT
	END
	
	--BANG GV_UVDT
	IF EXISTS (SELECT * FROM GV_UVDT WHERE MSDT = @MSDT)
	BEGIN
		SELECT @SOGV_CHAMDIEM += COUNT(*), @TONGDIEM += SUM(DIEM)
		FROM GV_UVDT
		WHERE MSDT = @MSDT
	END

	--TINH DIEM TRUNG BINH
	SELECT @AGV = @TONGDIEM / @SOGV_CHAMDIEM
END
GO

--2.1. THỰC THI
DECLARE @MSDT CHAR(6), @AGV FLOAT
SET @MSDT = '97005'

EXEC PROC_DETAI_AGV @MSDT, @AGV OUTPUT
PRINT N'DIEM TRUNG BINH CUA DE TAI ' + @MSDT + ': ' + CAST(@AGV AS VARCHAR)
GO

--2.2. KIỂM TRA
DECLARE @MSDT CHAR(6)
SET @MSDT = '97005'

SELECT * FROM GV_HDDT WHERE MSDT = @MSDT
SELECT * FROM GV_PBDT WHERE MSDT = @MSDT
SELECT * FROM GV_UVDT WHERE MSDT = @MSDT
GO

--2.3. KHÔI PHỤC DỮ LIỆU (NẾU CÓ)


--2.4. XÓA
DROP PROC PROC_DETAI_AGV
GO



------------------------------------------------------------------------------------------------------------------------------------
--CAU 3
--3. Đưa vào TENGV trả ra: SDT của giáo viên đó, nếu không tìm thấy trả về 0.
--Nếu trùng tên thì có báo lỗi không? Tại sao? Làm sao để hiện thông báo có bao 
--nhiêu giáo viên trùng tên và trả về các SDT.

--Nếu trùng tên giáo viên thì không báo lỗi, vì tên giáo viên không phải là khóa chính nên có thể trùng nhau.

CREATE PROC PROC_TENGV_SDT
	@TENGV NVARCHAR(30), @SODT VARCHAR(10) OUTPUT
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM GIAOVIEN WHERE TENGV = @TENGV)
	BEGIN
		PRINT 'TEN GIAO VIEN KHONG TON TAI'
		RETURN 0
	END

	ELSE
	BEGIN
		DECLARE @SOGV_TRUNG_SDT INT
		SELECT @SOGV_TRUNG_SDT = COUNT(SODT) 
		FROM GIAOVIEN WHERE TENGV = @TENGV

		IF @SOGV_TRUNG_SDT > 1
		BEGIN
			PRINT N'CÓ ' + CAST(@SOGV_TRUNG_SDT AS VARCHAR) + ' GIÁO VIÊN TRÙNG TÊN!'
			SELECT SODT, MSGV FROM GIAOVIEN WHERE TENGV = @TENGV --in ra bảng các SDT của tên giáo viên đó
		END
		ELSE
			SELECT @SODT = SODT FROM GIAOVIEN WHERE TENGV = @TENGV
	END
END
GO

--3.1. THỰC THI
/*  
INSERT INTO GIAOVIEN VALUES ('123', N'Trần Trung', 'THUDUC', '0123456789', 2, 1999)
SELECT * FROM GIAOVIEN
DELETE FROM GIAOVIEN WHERE MSGV = '123'		
*/
--Thành công
--Trường hợp 1: không bị trùng tên giáo viên
DECLARE @TENGV NVARCHAR(30) = N'Trần Trung',
	@SODT VARCHAR(10)
EXEC PROC_TENGV_SDT @TENGV, @SODT OUTPUT
PRINT 'SDT CUA GIAO VIEN ' + @TENGV + ' LA ' + @SODT
GO
--Trường hợp 2: bị trùng tên giáo viên
INSERT INTO GIAOVIEN VALUES ('123', N'Trần Trung', 'THUDUC', '0123456789', 2, 1999)

DECLARE @TENGV NVARCHAR(30) = N'Trần Trung',
	@SODT VARCHAR(10)
EXEC PROC_TENGV_SDT @TENGV, @SODT OUTPUT
PRINT 'SDT CUA GIAO VIEN ' + @TENGV + ' LA ' + @SODT
GO

--Thất bại
DECLARE @TENGV NVARCHAR(30) = N'NGUYEN VAN A',
	@SODT VARCHAR(10)
EXEC PROC_TENGV_SDT @TENGV, @SODT OUTPUT
PRINT 'SDT CUA GIAO VIEN ' + @TENGV + ' LA ' + @SODT
GO

--3.2. KIỂM TRA
SELECT * FROM GIAOVIEN

--3.3. KHÔI PHỤC DỮ LIỆU (NẾU CÓ)
DELETE FROM GIAOVIEN WHERE MSGV = '123'	

--3.4. XÓA
DROP PROC PROC_TENGV_SDT
GO



---------------------------------------------------------------------------------------------------------
--CAU 4
--4. Đưa vào MSHD cho biết: Điểm trung bình các đề tài của hội đồng đó.

CREATE PROC PROC_HOIDONG_AGV
	@MSHD INT, @AGV FLOAT OUTPUT
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM HOIDONG WHERE MSHD = @MSHD)
	BEGIN
		PRINT 'MSHD KHONG TON TAI'
		RETURN 0
	END

	DECLARE @TONGDIEM FLOAT = 0, @COUNT INT = 0

	--BANG GV_HDDT
	IF EXISTS (SELECT * FROM HOIDONG_GV, GV_HDDT 
					WHERE HOIDONG_GV.MSGV = GV_HDDT.MSGV AND MSHD = @MSHD)
	BEGIN
		SELECT @TONGDIEM = SUM(DIEM), @COUNT = COUNT(*)
		FROM HOIDONG_GV JOIN GV_HDDT ON HOIDONG_GV.MSGV = GV_HDDT.MSGV
		WHERE MSHD = @MSHD
	END

	--BANG GV_PBDT
	IF EXISTS (SELECT * FROM HOIDONG_GV, GV_PBDT 
					WHERE HOIDONG_GV.MSGV = GV_PBDT.MSGV AND MSHD = @MSHD)
	BEGIN
		SELECT @TONGDIEM += SUM(DIEM), @COUNT += COUNT(*)
		FROM HOIDONG_GV JOIN GV_PBDT ON HOIDONG_GV.MSGV = GV_PBDT.MSGV
		WHERE MSHD = @MSHD
	END

	--BANG GV_UVDT
	IF EXISTS (SELECT * FROM HOIDONG_GV, GV_UVDT
					WHERE HOIDONG_GV.MSGV = GV_UVDT.MSGV AND MSHD = @MSHD)
	BEGIN
		SELECT @TONGDIEM += SUM(DIEM), @COUNT += COUNT(*)
		FROM HOIDONG_GV JOIN GV_UVDT ON HOIDONG_GV.MSGV = GV_UVDT.MSGV
		WHERE MSHD = @MSHD
	END

	SELECT @AGV = @TONGDIEM / @COUNT
END
GO

--4.1. THỰC THI
--Thành công
DECLARE @MSHD INT = 2, @AGV FLOAT
EXEC PROC_HOIDONG_AGV @MSHD, @AGV OUTPUT
PRINT 'DIEM TRUNG BINH CAC DE TAI CUA HOI DONG (MSHD: ' 
		+ CAST(@MSHD AS VARCHAR) + ') LA ' + CAST(@AGV AS VARCHAR)
GO

--Thất bại
DECLARE @MSHD INT = 10, @AGV FLOAT
EXEC PROC_HOIDONG_AGV @MSHD, @AGV OUTPUT
PRINT 'DIEM TRUNG BINH CAC DE TAI CUA HOI DONG (MSHD: ' 
		+ CAST(@MSHD AS VARCHAR) + ') LA ' + CAST(@AGV AS VARCHAR)
GO

--4.2. KIỂM TRA
DECLARE @MSHD INT = 2
SELECT * FROM HOIDONG_GV JOIN GV_HDDT ON HOIDONG_GV.MSGV = GV_HDDT.MSGV WHERE MSHD = @MSHD
SELECT * FROM HOIDONG_GV JOIN GV_PBDT ON HOIDONG_GV.MSGV = GV_PBDT.MSGV WHERE MSHD = @MSHD
SELECT * FROM HOIDONG_GV JOIN GV_UVDT ON HOIDONG_GV.MSGV = GV_UVDT.MSGV WHERE MSHD = @MSHD
GO

--4.3. KHÔI PHỤC DỮ LIỆU (NẾU CÓ)


--4.4. XÓA
DROP PROC PROC_HOIDONG_AGV
GO



-----------------------------------------------------------------------------------------------------------------------------
--CAU 5
--5. Đưa vào TENGV cho biết: Số đề tài hướng dẫn, số đề tài phản biện do giáo 
--viên đó phụ trách. Nếu trùng tên thì có báo lỗi không hay hệ thống sẽ đếm tất 
--cả các đề tài của những giáo viên trùng tên đó?

--Nêu trùng tên, hệ thống không báo lỗi, vì tên giáo viên không phải khóa chính. 
--Hệ thống sẽ đếm tất cả các đề tài của từng giáo viên đó (dùng MSGV để phân biệt cho từng GV).

CREATE PROC PROC_TENGV_DT
	@TENGV NVARCHAR(30),
	@DTHD INT OUTPUT, @DTPB INT OUTPUT
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM GIAOVIEN WHERE TENGV = @TENGV)
	BEGIN
		PRINT N'TEN GIAO VIEN KHONG TON TAI'
		RETURN 0
	END

	DECLARE @GV_TRUNG INT
	SELECT @GV_TRUNG = COUNT(MSGV) FROM GIAOVIEN WHERE TENGV = @TENGV

	IF @GV_TRUNG > 1
	BEGIN
		PRINT N'CÓ ' + CAST(@GV_TRUNG AS VARCHAR) + ' GIÁO VIÊN TRÙNG TÊN!'

		SELECT T1.MSGV, SO_DTDH, SO_DTPB
		FROM
				--BANG GV_HDDT
				(SELECT GV.MSGV, COUNT(MSDT) AS SO_DTDH
				FROM GIAOVIEN GV LEFT JOIN GV_HDDT HD ON GV.MSGV = HD.MSGV
				GROUP BY GV.MSGV) T1
			JOIN
				--BANG GV_PBDT
				(SELECT GV.MSGV, COUNT(MSDT) AS SO_DTPB
				FROM GIAOVIEN GV LEFT JOIN GV_PBDT PB ON GV.MSGV = PB.MSGV
				GROUP BY GV.MSGV) T2
			ON T1.MSGV = T2.MSGV
		WHERE T1.MSGV IN (SELECT MSGV FROM GIAOVIEN WHERE TENGV = @TENGV)
	END

	ELSE
	BEGIN
		SELECT @DTHD = COUNT(HD.MSDT), @DTPB = COUNT(PB.MSDT)
		FROM (GIAOVIEN GV LEFT JOIN GV_HDDT HD ON GV.MSGV = HD.MSGV)
				LEFT JOIN GV_PBDT PB ON GV.MSGV = PB.MSGV
		WHERE TENGV = @TENGV
	END
END
GO

--5.1. THỰC THI
/*  
INSERT INTO GIAOVIEN VALUES ('123', N'Trần Trung', 'THUDUC', '0123456789', 2, 1999)
SELECT * FROM GIAOVIEN
DELETE FROM GIAOVIEN WHERE MSGV = '123'		
*/
--Thành công
--Trường hợp 1: không bị trùng tên giáo viên
DECLARE @TENGV NVARCHAR(30) = N'Trần Trung', 
		@SO_DTHD INT, @SO_DTPB INT
EXEC PROC_TENGV_DT @TENGV, @SO_DTHD OUTPUT, @SO_DTPB OUTPUT
PRINT 'SO LUONG DTHD CUA GIAO VIEN ' + @TENGV + ' LA ' + CAST(@SO_DTHD AS VARCHAR)
PRINT 'SO LUONG DTPB CUA GIAO VIEN ' + @TENGV + ' LA ' + CAST(@SO_DTPB AS VARCHAR)
GO

--Trường hợp 2: bị trùng tên giáo viên
INSERT INTO GIAOVIEN VALUES ('123', N'Trần Trung', 'THUDUC', '0123456789', 2, 1999)

DECLARE @TENGV NVARCHAR(30) = N'Trần Trung', 
		@SO_DTHD INT, @SO_DTPB INT
EXEC PROC_TENGV_DT @TENGV, @SO_DTHD OUTPUT, @SO_DTPB OUTPUT
PRINT 'SO LUONG DTHD CUA GIAO VIEN ' + @TENGV + ' LA ' + CAST(@SO_DTHD AS VARCHAR)
PRINT 'SO LUONG DTPB CUA GIAO VIEN ' + @TENGV + ' LA ' + CAST(@SO_DTPB AS VARCHAR)
GO

--Thất bại
DECLARE @TENGV NVARCHAR(30) = N'NGUYEN VAN A',
		@SO_DTHD INT, @SO_DTPB INT
EXEC PROC_TENGV_DT @TENGV, @SO_DTHD OUTPUT, @SO_DTPB OUTPUT
PRINT 'SO LUONG DTHD CUA GIAO VIEN ' + @TENGV + ' LA ' + CAST(@SO_DTHD AS VARCHAR)
PRINT 'SO LUONG DTPB CUA GIAO VIEN ' + @TENGV + ' LA ' + CAST(@SO_DTPB AS VARCHAR)
GO

--5.2. KIỂM TRA
DECLARE @TENGV NVARCHAR(30) = N'Trần Trung'
SELECT B.MSGV, TENGV, MSDT AS MS_DTHD 
	FROM GV_HDDT A RIGHT JOIN GIAOVIEN B ON A.MSGV = B.MSGV  WHERE TENGV = @TENGV

SELECT B.MSGV, TENGV, MSDT AS MS_DTPB
	FROM GV_PBDT A RIGHT JOIN GIAOVIEN B ON A.MSGV = B.MSGV WHERE TENGV = @TENGV
GO

--5.3. KHÔI PHỤC DỮ LIỆU (NẾU CÓ)
DELETE FROM GIAOVIEN WHERE MSGV = '123'	
GO

--5.4. XÓA
DROP PROC PROC_TENGV_DT
GO
