-----------------------------------C. TRIGGER------------------------------------------

USE QLDT
GO


---------------------------------------------------------------------------------------------------
--CAU 1
--1. Tạo Trigger thỏa mãn điều kiện khi xóa một đề tài sẽ xóa các thông tin liên quan.

CREATE TRIGGER TRG_DELETE_DETAI
ON DETAI
INSTEAD OF DELETE --BEFORE TRIGGER
AS
BEGIN
	DECLARE @MSDT CHAR(6)
	SELECT @MSDT = MSDT FROM DELETED

	--Kiểm tra DETAI có dữ liệu hay không
	IF @@ROWCOUNT = 0
	BEGIN
		PRINT 'BANG DETAI KHONG CO DU LIEU'
		RETURN
	END

	--XOA CAC BANG LIEN QUAN
	DELETE FROM SV_DETAI WHERE MSDT = @MSDT
	DELETE FROM GV_HDDT WHERE MSDT = @MSDT
	DELETE FROM GV_PBDT WHERE MSDT = @MSDT
	DELETE FROM GV_UVDT WHERE MSDT = @MSDT
	DELETE FROM HOIDONG_DT WHERE MSDT = @MSDT

	DELETE FROM DETAI WHERE MSDT = @MSDT

	PRINT N'XOA THANH CONG'
END
GO

--1.1. THỰC THI
--Vô hiệu hóa các ràng buộc liên quan bảng DETAI
ALTER TABLE SV_DETAI NOCHECK CONSTRAINT ALL
ALTER TABLE GV_HDDT NOCHECK CONSTRAINT ALL
ALTER TABLE GV_PBDT NOCHECK CONSTRAINT ALL
ALTER TABLE GV_UVDT NOCHECK CONSTRAINT ALL
ALTER TABLE HOIDONG_DT NOCHECK CONSTRAINT ALL

DELETE FROM DETAI WHERE MSDT = '97001'

--Kích hoạt lại các ràng buộc liên quan bảng DETAI
ALTER TABLE SV_DETAI CHECK CONSTRAINT ALL
ALTER TABLE GV_HDDT CHECK CONSTRAINT ALL
ALTER TABLE GV_PBDT CHECK CONSTRAINT ALL
ALTER TABLE GV_UVDT CHECK CONSTRAINT ALL
ALTER TABLE HOIDONG_DT CHECK CONSTRAINT ALL
GO

--1.2. KIỂM TRA
SELECT * FROM DETAI
SELECT * FROM SV_DETAI
SELECT * FROM GV_HDDT 
SELECT * FROM GV_PBDT
SELECT * FROM GV_UVDT
SELECT * FROM HOIDONG_DT
GO

--1.3. KHÔI PHỤC DỮ LIỆU (NẾU CÓ)
INSERT INTO DETAI VALUES ('97001', N'Quản lý thư viện')
INSERT INTO SV_DETAI VALUES ('13520003', '97001')
INSERT INTO GV_HDDT VALUES ('201', '97001', 8), ('205', '97001', 9)
INSERT INTO GV_PBDT VALUES ('202', '97001', 7)
INSERT INTO GV_UVDT VALUES ('203', '97001', 7), ('204', '97001', 9), ('205', '97001', 8)
INSERT INTO HOIDONG_DT VALUES ('1', '97001', N'Được'), ('2', '97001', N'Không'), ('3', '97001', N'Không')
GO

--1.4. XÓA
DROP TRIGGER TRG_DELETE_DETAI
GO



------------------------------------------------------------------------------------------
--CAU 2
--2. Tạo Trigger thỏa mãn ràng buộc là khi đổi 1 mã số giáo viên (MSGV) thì sẽ 
--thay đổi các thông tin liên quan.

CREATE TRIGGER TRG_UPDATE_GIAOVIEN
ON GIAOVIEN
FOR UPDATE
AS
BEGIN
	DECLARE @MSGV_I INT, @MSGV_D INT
	SELECT @MSGV_I = MSGV FROM INSERTED
	SELECT @MSGV_D = MSGV FROM DELETED

	--Kiểm tra bảng GIAOVIEN có dữ liệu hay không
	IF @@ROWCOUNT = 0
	BEGIN
		PRINT 'BANG GIAOVIEN KHONG CHUA DU LIEU'
		RETURN
	END

	--UPDATE CAC BANG LIEN QUAN
	UPDATE GV_HV_CN SET MSGV = @MSGV_I WHERE MSGV = @MSGV_D
	UPDATE GV_HDDT SET MSGV = @MSGV_I WHERE MSGV = @MSGV_D
	UPDATE GV_PBDT SET MSGV = @MSGV_I WHERE MSGV = @MSGV_D
	UPDATE GV_UVDT SET MSGV = @MSGV_I WHERE MSGV = @MSGV_D
	UPDATE HOIDONG SET MSGV = @MSGV_I WHERE MSGV = @MSGV_D
	UPDATE HOIDONG_GV SET MSGV = @MSGV_I WHERE MSGV = @MSGV_D

	PRINT 'UPDATE MSGV THANH CONG'
END
GO

--2.1. THỰC THI
--Vô hiệu hóa các ràng buộc liên quan bảng GIAOVIEN
ALTER TABLE GV_HV_CN NOCHECK CONSTRAINT ALL
ALTER TABLE GV_HDDT NOCHECK CONSTRAINT ALL
ALTER TABLE GV_PBDT NOCHECK CONSTRAINT ALL
ALTER TABLE GV_UVDT NOCHECK CONSTRAINT ALL
ALTER TABLE HOIDONG NOCHECK CONSTRAINT ALL
ALTER TABLE HOIDONG_GV NOCHECK CONSTRAINT ALL

UPDATE GIAOVIEN SET MSGV = '123' WHERE MSGV = '201'

--Kích hoạt lại các ràng buộc liên quan bảng GIAOVIEN
ALTER TABLE GV_HV_CN CHECK CONSTRAINT ALL
ALTER TABLE GV_HDDT CHECK CONSTRAINT ALL
ALTER TABLE GV_PBDT CHECK CONSTRAINT ALL
ALTER TABLE GV_UVDT CHECK CONSTRAINT ALL
ALTER TABLE HOIDONG CHECK CONSTRAINT ALL
ALTER TABLE HOIDONG_GV CHECK CONSTRAINT ALL
GO

--2.2. KIỂM TRA
SELECT * FROM GIAOVIEN
SELECT * FROM GV_HV_CN
SELECT * FROM GV_HDDT 
SELECT * FROM GV_PBDT
SELECT * FROM GV_UVDT
SELECT * FROM HOIDONG
SELECT * FROM HOIDONG_GV
GO

--2.3. KHÔI PHỤC DỮ LIỆU (NẾU CÓ)
--Vô hiệu hóa các ràng buộc liên quan bảng GIAOVIEN
ALTER TABLE GV_HV_CN NOCHECK CONSTRAINT ALL
ALTER TABLE GV_HDDT NOCHECK CONSTRAINT ALL
ALTER TABLE GV_PBDT NOCHECK CONSTRAINT ALL
ALTER TABLE GV_UVDT NOCHECK CONSTRAINT ALL
ALTER TABLE HOIDONG NOCHECK CONSTRAINT ALL
ALTER TABLE HOIDONG_GV NOCHECK CONSTRAINT ALL

UPDATE GIAOVIEN SET MSGV = '201' WHERE MSGV = '123'

--Kích hoạt lại các ràng buộc liên quan bảng GIAOVIEN
ALTER TABLE GV_HV_CN CHECK CONSTRAINT ALL
ALTER TABLE GV_HDDT CHECK CONSTRAINT ALL
ALTER TABLE GV_PBDT CHECK CONSTRAINT ALL
ALTER TABLE GV_UVDT CHECK CONSTRAINT ALL
ALTER TABLE HOIDONG CHECK CONSTRAINT ALL
ALTER TABLE HOIDONG_GV CHECK CONSTRAINT ALL
GO

--2.4. XÓA
DROP TRIGGER TRG_UPDATE_GIAOVIEN
GO



---------------------------------------------------------------------------------------------------------
--CAU 3
--3. Tạo Trigger thỏa mãn ràng buộc là một hội đồng không quá 10 đề tài. Dùng 
--“Group by” có được không? Giải thích.

--Có thể sử dụng "Group by"
--Giải thích:
/*
CREATE TRIGGER TRG_HOIDONG_DT_Max10
ON HOIDONG_DT
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @COUNT INT
	SELECT @COUNT = CNT
	FROM
		(SELECT MSHD, COUNT(*) AS CNT
		FROM HOIDONG_DT
		GROUP BY MSHD) T1, INSERTED T2
	WHERE T1.MSHD = T2.MSHD

	IF @COUNT > 10
	BEGIN
		PRINT N'Lỗi!!! 1 hội đồng tối đa 10 đề tài'
		ROLLBACK TRANSACTION
	END
	ELSE
		PRINT N'THÀNH CÔNG'
END
GO
*/

CREATE TRIGGER TRG_HOIDONG_DT_Max10
ON HOIDONG_DT
FOR INSERT, UPDATE
AS
BEGIN
	IF (SELECT COUNT(*)
		FROM HOIDONG_DT T1, INSERTED T2
		WHERE T1.MSHD = T2.MSHD) > 10
	BEGIN
		PRINT N'Lỗi!!! 1 hội đồng tối đa 10 đề tài'
		ROLLBACK TRANSACTION
	END
	ELSE
		PRINT N'THÀNH CÔNG'
END
GO

--3.1. THỰC THI
--Thành công
UPDATE HOIDONG_DT SET MSDT = '97006' WHERE MSHD = 3 AND MSDT = '97001'

INSERT INTO HOIDONG_DT VALUES(3, '97006', 'SDFD')

--3.2. KIỂM TRA
SELECT * FROM HOIDONG_DT
GO

--3.3. KHÔI PHỤC DỮ LIỆU (NẾU CÓ)
--UPDATE
UPDATE HOIDONG_DT SET MSDT = '97001' WHERE MSHD = 3 AND MSDT = '97006'

--INSERT
DELETE FROM HOIDONG_DT WHERE MSDT = '97006'

--3.4. XÓA
DROP TRIGGER TRG_HOIDONG_DT_Max10
GO



---------------------------------------------------------------------------------
--CAU 4
--4. Tạo Trigger thỏa mãn ràng buộc là một đề tài không quá 2 sinh viên. Dùng 
--“Group by” có được không? Giải thích.

--Có thể dùng "Group by"
--Giải thích:
/*
CREATE TRIGGER TRG_SV_DETAI_Max2
ON SV_DETAI
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @COUNT INT
	SELECT @COUNT = CNT
	FROM
		(SELECT COUNT(*) AS CNT, MSDT
		FROM SV_DETAI
		GROUP BY MSDT) T1, INSERTED T2
	WHERE T1.MSDT = T2.MSDT

	IF @COUNT > 2
	BEGIN
		PRINT N'Lỗi!!! 1 đề tài chỉ được tối đa 2 sinh viên'
		ROLLBACK TRANSACTION
	END
	ELSE
		PRINT N'THÀNH CÔNG'
END
GO
*/

CREATE TRIGGER TRG_SV_DETAI_Max2
ON SV_DETAI
FOR INSERT, UPDATE
AS
BEGIN
	IF (SELECT COUNT(*)
		FROM SV_DETAI T1, INSERTED T2
		WHERE T1.MSDT = T2.MSDT) > 2
	BEGIN
		PRINT N'Lỗi!!! 1 đề tài chỉ được tối đa 2 sinh viên'
		ROLLBACK TRANSACTION
	END
	ELSE
		PRINT N'THÀNH CÔNG'
END
GO

--4.1. THỰC THI
--Thành công
UPDATE SV_DETAI SET MSDT = '97001' WHERE MSSV = '13520001'

INSERT INTO SV_DETAI VALUES('13520001', '97001')

--Thất bại
UPDATE SV_DETAI SET MSDT = '97005' WHERE MSSV = '13520001'

INSERT INTO SV_DETAI VALUES ('13520001', '97005')

--4.2. KIỂM TRA
SELECT * FROM SV_DETAI 
GO

--4.3. KHÔI PHỤC DỮ LIỆU (NẾU CÓ)
--UPDATE
UPDATE SV_DETAI SET MSDT = '97004' WHERE MSSV = '13520001'

--INSERT
DELETE FROM SV_DETAI WHERE MSDT = '97001' AND MSSV = '13520001'

--4.4. XÓA
DROP TRIGGER TRG_SV_DETAI_Max2
GO



-----------------------------------------------------------------------------------
--CAU 5
--5. Tạo Trigger thỏa mãn ràng buộc là một giáo viên muốn có học hàm PGS 
--phải là tiến sĩ.

CREATE TRIGGER TRG_GIAOVIEN_PGS
ON GIAOVIEN
FOR UPDATE
AS
BEGIN
	IF (SELECT MSHH FROM INSERTED) = 1 
		AND
		(SELECT MSHV
		FROM GV_HV_CN T1, INSERTED T2
		WHERE T1.MSGV = T2.MSGV) != 4
	BEGIN
		PRINT N'Lỗi! Học hàm PGS (MSHH 1) thì phải là Tiến sĩ (MSHV 4)'
		ROLLBACK TRANSACTION
	END
	ELSE
		PRINT N'THÀNH CÔNG'
END
GO

--5.1. THỰC THI
--Thành công
UPDATE GV_HV_CN SET MSHV = 4 WHERE MSGV = '204'

UPDATE GIAOVIEN SET MSHH = 1 WHERE MSGV = '204'

--Thất bại
UPDATE GIAOVIEN SET MSHH = 1 WHERE MSGV = '204'


--5.2. KIỂM TRA
SELECT * FROM GIAOVIEN
SELECT * FROM GV_HV_CN
GO

--5.3. KHÔI PHỤC DỮ LIỆU (NẾU CÓ)
UPDATE GV_HV_CN SET MSHV = 3 WHERE MSGV = '204'
UPDATE GIAOVIEN SET MSHH = 2 WHERE MSGV = '204'

--5.4. XÓA
DROP TRIGGER TRG_GIAOVIEN_PGS
GO




